### ISSUE TITLE
Using Drivetrains that aren't WPILIB Subsystems

### ISSUE THREAD

**Issue by alexanderswerdlow** [Team319/BobTrajectory#35]
Is there a recommended way of doing this? (I assume returning null would break things).

**Comment by notmattlythgoe** [comment]
Sorry we didn't get back to you sooner. No there is no way to do this in the old version of the code. The new version of BobTrajectory is removing the following part of the library and will only be a path generation library. It will however be completely independent of the WPILIB libraries.
